[book]
authors = ["Cameron Wells"]
language = "en"
multilingual = false
src = "src"
title = "Trimble Creator Node Documentation"

[output.html]
no-section-label = true
fold.enable = true
fold.level = 0
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.search]
limit-results = 5
